# .travis.yml
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
env:
  - CXX=g++-4.8
  global:
    - NPM_VERSION="^2.0.0"
install: npm install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
